# Generated by Django 4.2.16 on 2026-01-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0230_readwise_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="filter_suggestions_by_language",
            field=models.BooleanField(default=False),
        ),
    ]
