# Generated by Django 5.2.14 on 2026-05-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0230_readwise_integration'),
        ('bookwyrm', '0231_sitesettings_block_incoming_search_and_more'),
    ]

    operations = [
    ]
